using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;

using Ragnarok;

namespace VoteSystem.Protocol.Model
{
    using Vote;

    /// <summary>
    /// ネットワークの投票を行います。
    /// </summary>
    public static class TestVoterList
    {
        private static int idCounter = 0;
        private static int liveCounter = 0;
        private static int anonymousCount = 0;

        private static string NextId
        {
            get
            {
                var id = Interlocked.Increment(ref idCounter);

                return id.ToString();
            }
        }

        private static VoterInfo CreateInfo(string name, string skill = null)
        {
            var liveData = (liveCounter++ < 30 ?
                new LiveData(LiveSite.NicoNama, "lv142093226") : null);
            var id = (anonymousCount++ < 100 ?
                Guid.NewGuid().ToString() : NextId);

            return new VoterInfo(id, name, skill)
            {
                LiveData = liveData,
            };
        }

        /// <summary>
        /// テスト用
        /// </summary>
        public static VoterList GetTestVoterList()
        {
            var list = new List<VoterInfo>
            {
                //CreateInfo("ーーーー", "----"),
                //CreateInfo("^'''''", "____"),
                CreateInfo("テスト", "０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９"),
                CreateInfo("９８７６５４３２１０９８７６５４３２１０", "テスト"),
                CreateInfo("フルチンパイルドライバー", "おつおつおつおつ今来たよ～　って終わってるしｗ"),
                CreateInfo("(｀・ω・´)", "永世15級"),
                CreateInfo("hoki", "ワシの手柄や"),
                CreateInfo("あすか", "はじめてだけど"),
                CreateInfo("うんｋお", "ダークフレイムマスター"),
                CreateInfo("えびきらい", "せっかくなので"),
                CreateInfo("えろじじぃ", "美少女リスナーふやしてちょ"),
                CreateInfo("かきふらい", "もう疲れました"),
                CreateInfo("ぐら", "主の義弟"),
                CreateInfo("これは",　"デスノートです"),
                CreateInfo("でびたん", "気力はもうない"),
                CreateInfo("とまと", "ご飯食べてくる"),
                CreateInfo("とまとりあ", "最初のｇｄｇｄが無くなる日"),
                CreateInfo("なっちゃん", "コメなんてうってあげない///"),
                CreateInfo("参加なんて無かった", "それでいいじゃないか"),
                CreateInfo("エヴィ初号機", "パターンオレンジ"),
                CreateInfo("コミュどうしよう", "やめとくか"),
                CreateInfo("ハワイアン初春", "真冬のハワイから"),
                CreateInfo("ボナンザ", "1分で4時間と戦う"),
                CreateInfo("以下", "人狼参加者一覧"),
                CreateInfo("関根", "名人"),
                CreateInfo("焼き鳥", "参加者のみなさんおつでした"),
                CreateInfo("将棋仮面", "途中からＲＯＭってたわ"),
                CreateInfo("人狼王", "早く頼みます"),
                CreateInfo("徳川", "大名"),
                CreateInfo("某視聴者", "６時間おつーした"),
                CreateInfo("明", "棋力竜王"),
                CreateInfo("えぶふらい", "もっとしたかった"),
                CreateInfo("紅茶", "皆さんお疲れ様でしたー"),
                CreateInfo("野月", "えびちゃんあいしてる"),
                CreateInfo("スタッフ", "棋聖戦みてました"),
                CreateInfo("master", "遅れてきたNOT真打"),
                CreateInfo("名無しのリスナー", "楽しかったよー"),
                CreateInfo("三窮名無し", "おもろかった"),
                CreateInfo("えびふらい", "ありがとうございました"),
                CreateInfo("あああ", "第二回もやってね"),
                CreateInfo("とりちゃん", "エビちゃんと西尾先生とスタッフの皆さんお疲れ様でした"),
                CreateInfo("之びふ5い", "戦いはまだ終わってない(経済的な意味で)"),
                CreateInfo("砂漠", "楽しかったです"),
                CreateInfo("大山康晴", "天国から"),
                CreateInfo("さぬき", "職場から見守ったよ～！"),
                CreateInfo("森内名人", "つまらん将棋をしてしまったんご"),
                CreateInfo("24歳の24棋士", "将棋盤がお茶臭い　"),
                CreateInfo("かぜましょうに", "またやりましょう"),
                CreateInfo("えびふらい", "面白かったですお疲れ様"),
                CreateInfo("ナンバー8", "お疲れ様でした"),
                CreateInfo("ozawa24", "勉強になりました"),
                CreateInfo("とっても", "お疲れ様"),
                CreateInfo("tukisima", "楽しかったよ～"),
                CreateInfo("通りすがりの誰か", "いつものエビちゃんだった"),
                CreateInfo("エスペラード", "悔しいお"),
                CreateInfo("２２銀", "エビさんスタッフのみなさん乙"),
                CreateInfo("ああああ", "お疲れ様でした"),
                CreateInfo("おつかれさま", "楽しかったけど難しかったー次は終盤に時間使おう"),
                CreateInfo("エナツ", "えびさん企画最高でした"),
                CreateInfo("あｍ", "楽しかったよー　"),
                CreateInfo("豊中の受け師", "楽しかったけど難しかったー次は終盤に時間使おう"),
                CreateInfo("言霊", "ミラーしてた人"),
                CreateInfo("あまちゃん", "楽しかった"),
                CreateInfo("espelade", "最高の企画でした"),
                CreateInfo("茶化し係", "楽しめたよー"),
                CreateInfo("スタッフ", "棋聖戦の休憩中"),
                CreateInfo("noda", "主もスタッフもお疲れ様でした"),
                CreateInfo("ふぁあ", "リスナーはそこまで勝ちにこだわってない"),
                CreateInfo("エビさんはスタッフでおいしくいただきました", "もっとしたかった"),
                CreateInfo("ヽ(*´∀｀*)ﾉ", "定番のファンタ。楽しかったです"),
                CreateInfo("hoki", "よくやった。よくやったよ・・・"),
                CreateInfo("将棋仮面", "バイト先から"),
                CreateInfo("野生", "おつおつでした"),
                CreateInfo("主にバリカンを", "髪長すぎｗ"),
                CreateInfo("渡辺明", "これがプロです"),
                CreateInfo("つーてんかく", "いい最終回だった"),
                CreateInfo("之びふ5い", "戦いはまだ終わってない(費用回収の意味で)　"),
                CreateInfo("じむ", "面白かったです"),
                CreateInfo("おれら", "またやろうね！"),
                CreateInfo("うんｋお", "乙彼でした"),
                CreateInfo("ああああ", "クジラ強くしろ"),
                CreateInfo("揚げ出し豆腐おいしい", "惜しかった！"),
                CreateInfo("選挙に行った都民", "雪かきで腰痛い"),
                CreateInfo("えびふらい", "GPSFish強すぎ"),
                CreateInfo("32歩", "この1手が誰も読めなかった"),
                CreateInfo("えばふらい", "強かった"),
                CreateInfo("とまと", "自動で名前取得したらええ"),
                CreateInfo("無名", "初めて最初から最後まで参加しました"),
                CreateInfo("とりふらい", "俺が本物だから！"),
                CreateInfo("エスペラード", "ハッシーに負けた"),
                CreateInfo("寄付金返せ", "はよ"),
                CreateInfo("機巧うんｋおは傷つかない", "負けたけど"),
                CreateInfo("ななし", "乙"),
                CreateInfo("あい", "うえお"),
                CreateInfo("え？", "異見わからん"),
                CreateInfo("あるつ", "頑張った"),
                CreateInfo("飯野愛", "かわいい"),
                CreateInfo("KK", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("兄貴", "見たい"),
                CreateInfo("けん", "むぎゅ♪"),
                CreateInfo("たかし", "やっほー"),
                CreateInfo("名前", "メッセージ"),
                CreateInfo("ひろみ", "楽しかったです"),
                CreateInfo("かつどん", "強かったわ"),
                CreateInfo("いけめん", "愛さんラブ"),
                CreateInfo("カモ", "ティロティロ"),
                CreateInfo("hikakoba", "ティロティロティロアーヤッチャッタヨー"),
                CreateInfo("すふぃあ", "面白かったよー"),
                CreateInfo("生湯葉", "楽しかった"),
                CreateInfo("アルス", "電王戦楽しみです"),
                CreateInfo("俺", "面白かったぜ－"),
                CreateInfo("BOU", "ﾃｨﾛﾃｨﾛ"),
                CreateInfo("針鼠", "かちたかったーーーーー"),
                CreateInfo("ニートマン", "ポナ山イケメン"),
                CreateInfo("シクラメン", "面白かったー"),
                CreateInfo("まろｐ", "みんながんばれええええええええええ"),
                CreateInfo("1013", "オツカレサマドスエ！"),
                CreateInfo("rzp", "将棋ファンでよかったーーー！"),
                CreateInfo("西尾", "GJ"),
                CreateInfo("ガキの使い", "ｱｰﾔｯﾁｬｯﾀﾖｰ↓↓"),
                CreateInfo("大山15世名人", "よかったよ"),
                CreateInfo("まじで", "乗るの？"),
                CreateInfo("名前", "メッセージ"),
                CreateInfo("男性", "角切りたかった"),
                CreateInfo("enzo", "楽しかった～♪"),
                CreateInfo("たまご", "ありがとう！"),
                CreateInfo("おお", "よろ"),
                CreateInfo("咲乃光", "楽しかったっす"),
                CreateInfo("mike猫", "楽しかった！"),
                CreateInfo("Mac", "お疲れ様"),
                CreateInfo("犬", "ワンワン"),
                CreateInfo("ルート", "おもしろかった！"),
                CreateInfo("劉邦", "たのしい"),
                CreateInfo("zip8", "─=≡Σ((((っ’ヮ’c)"),
                CreateInfo("けん", "むぎゅむぎゅ♪"),
                CreateInfo("syoU", "勝機！"),
                CreateInfo("ふぁいあ", "次回もお願いします。"),
                CreateInfo("xnanasu", "おつかれ"),
                CreateInfo("野生の羽生", "セイカイデス"),
                CreateInfo("ふらふら", "棋士は本当に強いんです"),
                CreateInfo("森内", "あ、負けました。"),
                CreateInfo("YT", "楽しかったよ"),
                CreateInfo("斉藤一", "たのしかった"),
                CreateInfo("げまー", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("そーすけ", "たのしかった"),
                CreateInfo("トトロ", "お疲れ様でした。"),
                CreateInfo("KK", "たのしそうだね"),
                CreateInfo("虎ケン", "凄く楽しかったのぜ！！"),
                CreateInfo("ぶりぶりざえもん", "よかった"),
                CreateInfo("シルコレ", "ありがとうございました"),
                CreateInfo("tk", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("野月", "一成まけろ"),
                CreateInfo("ミズ", "ロムってたけど楽しかったー"),
                CreateInfo("yoshi", "楽しかった"),
                CreateInfo("名前", "メッセージ"),
                CreateInfo("まつぼう", "めっちゃおもろかった"),
                CreateInfo("きんたろ", "たのしかったを"),
                CreateInfo("ミナト", "負けてくやしいぜー"),
                CreateInfo("カキフライ", "今日はみなさんお疲れ様でした"),
                CreateInfo("小鳥", "面白かったです"),
                CreateInfo("コットン", "楽しかったお"),
                CreateInfo("ながと", "くやしい"),
                CreateInfo("３１４", "よかった"),
                CreateInfo("えび頑張った", "ガレリア最高！"),
                CreateInfo("みきお", "愛ちゃんおつかれ"),
                CreateInfo("伊能忠敬", "歩き疲れた…"),
                CreateInfo("shortTT", "たのしかった"),
                CreateInfo("まる", "おもしろかったです"),
                CreateInfo("山本一成", "１００万ありがとう"),
                CreateInfo("如月", "楽しかった"),
                CreateInfo("野生の名人", "あ、負けました"),
                CreateInfo("山崎誠", "愛ちゃんかわいい"),
                CreateInfo("運輸省", "運ばせてよー"),
                CreateInfo("s", "おつ"),
                CreateInfo("山本", "一〇〇〇〇〇〇あげます"),
                CreateInfo("リサリサ", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("マコチン", "乙カレー"),
                CreateInfo("HIRO", "強すぎ"),
                CreateInfo("渡辺王将", "あっ勝ちました"),
                CreateInfo("さくまろーん", "こんにちわ！"),
                CreateInfo("羽生", "羽生じゃないよ"),
                CreateInfo("あ", "あ"),
                CreateInfo("石川典行", "京都府知事選挙出るよ"),
                CreateInfo("名前", "コメント"),
                CreateInfo("[名前]", "[コメント]"),
                CreateInfo("ポナポナ", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("揚出豆腐", "R2800のえびふらいさんなんか喋って！"),
                CreateInfo("なまえ", "メッセ"),
                CreateInfo("bps", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("自分の名前", "一言メッセージ"),
                CreateInfo("ごろ", "ｵﾓｼﾛｶｯﾀﾖｰ"),
                CreateInfo("え", "ﾀﾉｼｶｯﾀﾈ"),
                CreateInfo("あっさー", "楽しかった"),
                CreateInfo("飯野", "かわいい"),
                CreateInfo("vlal", "将棋愛してる"),
                CreateInfo("ふなくにゃ", "楽しかったれす"),
                CreateInfo("ﾃｨﾛ", "お疲れ様でした"),
                CreateInfo("8", "お疲れ様でした"),
                CreateInfo("MDCS", "楽しかった"),
                CreateInfo("まるお", "お金下さい"),
                CreateInfo("たかじん", "そこまで言って委員会"),
                CreateInfo("まさ", "楽しかったです"),
                CreateInfo("くすくす", "面白かった"),
                CreateInfo("揚出豆腐", "R2800のえびふらいさんなんか喋ってよ！"),
                CreateInfo("自分の名前", "メッセージ"),
                CreateInfo("森内", "あ、まけました"),
                CreateInfo("坂本", "８８８８８８８８８８８"),
                CreateInfo("3FREEZE", "愛ちゃん応援してますー"),
                CreateInfo("とんかつ", "あああああああああああああああああああああああああ"),
                CreateInfo("ぐんも", "ポナンザ強いなあ"),
                CreateInfo("Clotie", "楽しかったー"),
                CreateInfo("ビンゴマスター", "ポナンザ強かった"),
                CreateInfo("ヒロキ", "疲れた"),
                CreateInfo("西尾", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("エリーゼ", "タノシカッタ"),
                CreateInfo("くろ", "次回もよろしく"),
                CreateInfo("ぽれぽれ", "なにするん？"),
                CreateInfo("たる", "頑張った"),
                CreateInfo("匿名希望", "ﾀﾉｼｶｯﾀﾈ"),
                CreateInfo("MA", "人類オワタ"),
                CreateInfo("まつぽん", "うおおおおおおおおお"),
                CreateInfo("のあ太", "ティロティロ"),
                CreateInfo("カニベース", "テスト"),
                CreateInfo("むぎ", "面白かった"),
                CreateInfo("えびの囲い", "つぎはかつ！！！"),
                CreateInfo("電王", "イエーイ(v^_^)"),
                CreateInfo("ore　来週からの勝負・・・結婚阻止ｶﾞﾝ(", "ﾟдﾟ)ｶﾞﾚ"),
                CreateInfo("あ", "愛ちゃんかわいかった"),
                CreateInfo("YK", "なんぞこれー"),
                CreateInfo("一成の嫁", "激おこプンプン"),
                CreateInfo("ドラステ", "ｵﾓｼﾛｶｯﾀﾃﾞｽ"),
                CreateInfo("たろう", "将棋最高ー"),
                CreateInfo("森内俊之", "あ、負けました"),
                CreateInfo("smalltree", "自分で考えよう"),
                CreateInfo("88", "たのしかった"),
                CreateInfo("ジョーカー", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("み", "おつ"),
                CreateInfo("おま", "面白かった"),
                CreateInfo("アジフライ", "山本さんうぎいいいい"),
                CreateInfo("ocean", "やしもんがんばれ～"),
                CreateInfo("ぽけん", "楽しかったYO"),
                CreateInfo("かｓ", "いええす"),
                CreateInfo("asdf", "乙"),
                CreateInfo("ハマ", "電王戦見るよ！！！"),
                CreateInfo("ARAKI", "記録させて"),
                CreateInfo("玉", "炎上しちゃいました"),
                CreateInfo("矢内", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("優", "疲れた！！楽しかった！！"),
                CreateInfo("俺だー！", "愛ちゃん愛してるー！"),
                CreateInfo("bps", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("プロ", "あ、参加しました"),
                CreateInfo("ティロ", "ティロ"),
                CreateInfo("ひろし", "またやって"),
                CreateInfo("YN", "５９角が悔しい。"),
                CreateInfo("きたみちお", "またやって！"),
                CreateInfo("瑛", "すごかった"),
                CreateInfo("えびちゃんだい", "えびえび"),
                CreateInfo("古田", "やほーー"),
                CreateInfo("不参加", "参加"),
                CreateInfo("な", "よろしくお願い申し上げます。機"),
                CreateInfo("ちか", "楽しかった"),
                CreateInfo("rain", "電王戦期待してます！！"),
                CreateInfo("ジー", "楽しかったった"),
                CreateInfo("おいか", "よかった"),
                CreateInfo("かっちゃん", "つぎはまけないぞ！"),
                CreateInfo("けんいちろう", "愛ちゃん可愛い"),
                CreateInfo("yt", "お疲れさまでした！次があれば勝ちましょ！"),
                CreateInfo("のりすけ", "？？？？"),
                CreateInfo("おすし", "お疲れ様でした"),
                CreateInfo("Rest48", "面白かった！"),
                CreateInfo("uma", "お疲れ様でした"),
                CreateInfo("モモンガ", "結婚がんばって"),
                CreateInfo("竜王名人", "あ、負けました"),
                CreateInfo("加藤一二三", "棒銀が好きです"),
                CreateInfo("ベランダ", "勝ちたかった"),
                CreateInfo("しっちゃん", "森下先生頑張れ！！"),
                CreateInfo("スプートニク", "オリジナルエンディング最高！"),
                CreateInfo("すな", "投了勢でした"),
                CreateInfo("いかるご", "いえあああ"),
                CreateInfo("むあ。", "おもしろかったｗ"),
                CreateInfo("さくこ", "将棋サイコー!!"),
                CreateInfo("asahi", "愛ちゃんかわいい"),
                CreateInfo("ママ犬", "楽しかったよー"),
                CreateInfo("け～た。", "おもしろかった。"),
                CreateInfo("羽生", "なんだ"),
                CreateInfo("ユヴェントス", "電王最強！"),
                CreateInfo("こんてす", "投了"),
                CreateInfo("モリ", "おつかれさまでした"),
                CreateInfo("シーサン", "電王戦楽しみにしてます"),
                CreateInfo("ﾃｨﾛ中", "お疲れさまー"),
                CreateInfo("野生のプロ２５２５", "次回は勝つぜ！"),
                CreateInfo("山谷", "大変おもしろかった"),
                CreateInfo("投了", "(´・ω・｀)ｱｰﾔｯﾁｬｯﾀﾖｰ"),
                CreateInfo("よくと", "将棋たのしい！"),
                CreateInfo("ras", "お疲れ様"),
                CreateInfo("鬼瓦", "いい戦いじゃっ他"),
                CreateInfo("ｐｐ", "おつかれ"),
                CreateInfo("えのたん", "えほえほえほ♪"),
                CreateInfo("ウラジミール・プーチン", "次は負けない"),
                CreateInfo("miredeli", "棋士頑張れ！！！！！"),
                CreateInfo("デラク", "すごく楽しかった"),
                CreateInfo("apple", "健闘した！"),
                CreateInfo("でず", "電王戦すごい楽しみにしてます！"),
                CreateInfo("John", "西尾せんせお疲れ！"),
                CreateInfo("タモリ", "明日も来てくれるかな？？"),
                CreateInfo("黒", "楽しかった！"),
                CreateInfo("kangoru", "おもしろかったぞー"),
                CreateInfo("愛", "好き?"),
                CreateInfo("にゃふ", "おつかれさまですーー(´∀｀)"),
                CreateInfo("めんげれ", "お疲れ様です！"),
                CreateInfo("シッダールタ", "面白かった"),
                CreateInfo("アッキー", "勝ちたかった"),
                CreateInfo("よしを", "やっふー＾＾"),
                CreateInfo("やしもん", "勝ちます＾＾"),
                CreateInfo("MSDT", "たのしかた"),
                CreateInfo("ミコト", "ありがとうございました"),
                CreateInfo("鯰", "おもろかったでー"),
                CreateInfo("は", "ファンタスティック☆"),
                CreateInfo("tsubasa", "しょうぎ"),
                CreateInfo("健治", "楽しかった"),
                CreateInfo("いつもん", "本番は勝つ"),
                CreateInfo("やあ", "いい企画でした！"),
                CreateInfo("ponanza", "結婚します"),
                CreateInfo("haifon", "楽しかったです"),
                CreateInfo("まけいぬ", "そんなことないやろ～"),
                CreateInfo("けん", "ポナンザ、強いよね"),
                CreateInfo("くらのん", "よかお"),
                CreateInfo("すずろ", "みんなおつかれー！"),
                CreateInfo("ここ", "ありがとう?！！"),
                CreateInfo("橋本", "ponanzaさん？強いよね？序盤・中盤・終盤・わけがわからないよ"),
                CreateInfo("ABC", "Ponanzaマジ許さん"),
                CreateInfo("参加", "すげーーわーーー"),
                CreateInfo("自分の名前", "ひとことメッセージ"),
                CreateInfo("えびふらい", "乙"),
                CreateInfo("自分の名前", "愛の言葉"),
                CreateInfo("野球好き", "西尾先生おつでした"),
                CreateInfo("ﾃｨﾛ", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("とと", "がんば"),
                CreateInfo("NEU!!!!", "お疲れ様でした"),
                CreateInfo("モロヘイヤ", "将棋最高"),
                CreateInfo("若島津", "愛ちゃんかわいい"),
                CreateInfo("廃刊", "ﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("皐月", "ﾃｨ・・・ﾃｨﾛ・・・・"),
                CreateInfo("みろ", "山本さん結婚して"),
                CreateInfo("野月", "乙"),
                CreateInfo("名人竜王", "あ、負けました"),
                CreateInfo("みけねこ太郎", "本当にお疲れ様でした。次回も楽しみにしてます！"),
                CreateInfo("ちーめろ", "うきょちかわいい"),
                CreateInfo("IKE", "お疲れサマー！"),
                CreateInfo("藤井", "終盤は俺に聞け！！！"),
                CreateInfo("やまだ", "面白かったまたお願いします"),
                CreateInfo("たぬぽん", "投了"),
                CreateInfo("ヤン", "楽しかった"),
                CreateInfo("PINE", "面白かった"),
                CreateInfo("こてつ", "ポナ強すぎ"),
                CreateInfo("seyu", "ぽなガンバ"),
                CreateInfo("カキフライ", "ﾃｨﾛﾃｨﾛ"),
                CreateInfo("オカシラ", "次は勝つぞ！"),
                CreateInfo("motto", "おつおつ"),
                CreateInfo("管", "第二弾よろしくお願いします"),
                CreateInfo("将棋ボーイ", "かわいい"),
                CreateInfo("メロン", "あいうえお"),
                CreateInfo("餅", "ポナンザ強かった"),
                CreateInfo("髭男爵", "ルネッサーンス"),
                CreateInfo("月", "この悔しさを屋敷先生に託します！！"),
                CreateInfo("なべや", "またやってー"),
                CreateInfo("城戸康輔", "楽しかったよ"),
                CreateInfo("あ", "面白かったです"),
                CreateInfo("イカフライ", "あいちゃんかわいいいいいいいいいい"),
                CreateInfo("ﾃｨﾛ", "山本さん結婚おめ～"),
                CreateInfo("ぐら", "皆様お疲れ様。えびちゃんご苦労様でしたまた配信で～"),
                CreateInfo("ゆふいん", "おつかれさまー"),
                CreateInfo("Ｔａｙａ", "楽しかったよ～"),
                CreateInfo("123", "8888888888888"),
                CreateInfo("みんこる", "愛ちゃん可愛い"),
                CreateInfo("すみ", "面白かったよ"),
                CreateInfo("ヤン", "愛ちゃん可愛い"),
                CreateInfo("矢倉党", "次も矢倉"),
                CreateInfo("ポスト", "よかったぞ！"),
                CreateInfo("ni", "次回も期待してます"),
                CreateInfo("ぼて", "ﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("てつし", "おつかれさまでした"),
                CreateInfo("りり", "おつかれさまー"),
                CreateInfo("ぽりん", "えびおつー"),
                CreateInfo("あとぅーし", "いえーい！！"),
                CreateInfo("イカフライ", "お疲れ様～"),
                CreateInfo("くま", "面白かった"),
                CreateInfo("レッドゲー", "わーーーーーーい"),
                CreateInfo("俺", "乙"),
                CreateInfo("吉田", "愛してる"),
                CreateInfo("aki", "楽しかった"),
                CreateInfo("a", "b"),
                CreateInfo("ika", "おつかれー"),
                CreateInfo("黒", "面白かったです"),
                CreateInfo("takim", "次は勝つ"),
                CreateInfo("将軍", "やったるで～"),
                CreateInfo("バナナ", "美味しい"),
                CreateInfo("野球好き", "電王戦期待してます"),
                CreateInfo("ただやん", "楽しかった"),
                CreateInfo("わわ", "おつー"),
                CreateInfo("メイ", "85玉"),
                CreateInfo("銀冠", "屋敷先生！仇を取って下さい！"),
                CreateInfo("クロワッサン", "おつ♪"),
                CreateInfo("マグ", "見たよ！"),
                CreateInfo("ウナ", "大衆酒場閉店"),
                CreateInfo("おつ", "ponanza強い"),
                CreateInfo("bobo", "たのしかった"),
                CreateInfo("おなりかずき", "楽しかった"),
                CreateInfo("皇帝　(?", "???? ??)?ﾌｩｳｩｳｩｳｳｳｩｳｳｳ"),
                CreateInfo("doku", "楽しかった"),
                CreateInfo("智井", "みんなよくがんばった！"),
                CreateInfo("めるたん", "わーい"),
                CreateInfo("レブロフ", "楽しかったです！"),
                CreateInfo("ロール", "楽しかった"),
                CreateInfo("スミソ", "たのしかったっすー"),
                CreateInfo("伊藤電王", "山本さん結婚資金大切になさって"),
                CreateInfo("ｐｐｒ", "面白かったです！"),
                CreateInfo("wann", "メッセージ"),
                CreateInfo("くら", "ティロティロ"),
                CreateInfo("忍者福島", "またよろしくお願いします"),
                CreateInfo("kamikaze", "やまもとっつあん破産しろ！ｗ"),
                CreateInfo("ぽにゃんざ", "楽しかったよー"),
                CreateInfo("Alsen", "ponanza強すぎィ！！"),
                CreateInfo("meimei", "熱い対局をありがとう！"),
                CreateInfo("西尾明", "角切り怖い"),
                CreateInfo("やま", "おもしろかった"),
                CreateInfo("ちょこあ", "西尾さん＆愛ちゃん応援してます！"),
                CreateInfo("猫", "また次回は勝ちたい！"),
                CreateInfo("きぬごし", "おつかれちゃん！"),
                CreateInfo("タキウチ", "がんばれbonanza"),
                CreateInfo("リライト", "楽しかったよ"),
                CreateInfo("ヅー", "お疲れ様でした、リベンジ希望です"),
                CreateInfo("五十鈴", "次は勝ちたいです（震え声"),
                CreateInfo("ネコ助", "これがリンネだ・・・"),
                CreateInfo("＾＾ｂ", "グッジョブ"),
                CreateInfo("ﾊﾞﾙｻｽ", "楽しかったよ～！また次回よろしくです！"),
                CreateInfo("葵", "面白かった"),
                CreateInfo("棋神", "わしの一手一手から将棋の真髄を学ぶが良い"),
                CreateInfo("ilk", "お疲れさま"),
                CreateInfo("rtaa", "楽しかったよ"),
                CreateInfo("いとこん", "楽しかった"),
                CreateInfo("咲き熊", "おもしろかったです"),
                CreateInfo("航", "面白かった"),
                CreateInfo("えんど", "飯野さんかわいい"),
                CreateInfo("蓮霞", "楽しかった"),
                CreateInfo("ふ", "おもろかったー"),
                CreateInfo("ぶりーず", "爆発しろ！！！"),
                CreateInfo("munepi", "ティロティロ"),
                CreateInfo("たろんぺ", "がんばります"),
                CreateInfo("みっちー", "つよかった"),
                CreateInfo("もっかん", "ふぇぇ・・・"),
                CreateInfo("ひー", "たののののしかかかっかったたた"),
                CreateInfo("ああああ", "面白かったです"),
                CreateInfo("加藤一二三", "うひょー"),
                CreateInfo("めりる", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("横山", "最高！"),
                CreateInfo("俺", "やっふー"),
                CreateInfo("無名", "ponanzaここに君臨す"),
                CreateInfo("なみ", "ティロ"),
                CreateInfo("シルブレ", "ティロティロ"),
                CreateInfo("あんどー", "Ponaつよいな！"),
                CreateInfo("還元", "電位"),
                CreateInfo("参加", "参加"),
                CreateInfo("黒０", "おもしろかった！またやって！"),
                CreateInfo("あれれ", "楽しかったです"),
                CreateInfo("そらまめ", "将棋おもろー"),
                CreateInfo("のいえ", "わーい"),
                CreateInfo("baby", "我敗れたり"),
                CreateInfo("マント", "みんな弱いな"),
                CreateInfo("とらねこ", "楽しかった"),
                CreateInfo("名前", "一言メッセージ"),
                CreateInfo("名前", "一言"),
                CreateInfo("アイムマイム　楽しかった", "こんな感じです"),
                CreateInfo("103", "がんばれ"),
                CreateInfo("名前", "バッチこい！"),
                CreateInfo("タンジール", "おもしろかったぞ。"),
                CreateInfo("くまくま", "面白かった"),
                CreateInfo("りゅー", "将棋わからないけど最後まで見てしまった"),
                CreateInfo("kox3", "面白かったよ"),
                CreateInfo("名前", "メッセージ"),
                CreateInfo("ﾃｨﾛﾃｨﾛ", "ﾌｧｱｱｱｱｱｱｱｱｱｱｱｱ"),
                CreateInfo("やの", "くやしー！"),
                CreateInfo("hunger32", "楽しかったです"),
                CreateInfo("きしりとーる", "すごく楽しかった！またやって欲しい！！！！"),
                CreateInfo("infineon", "楽しかったです"),
                CreateInfo("銭形", "本戦では負けないよ！"),
                CreateInfo("けぃたん", "楽しかった。"),
                CreateInfo("アセチル", "ティロティロ"),
                CreateInfo("ぽろろ", "(´・ω・`)"),
                CreateInfo("りかと。", "みんなお疲れ！"),
                CreateInfo("やす", "面白かった"),
                CreateInfo("TT", "よかった"),
                CreateInfo("エムバイエ", "愛ちゃん大好き"),
                CreateInfo("あｑｗｓで", "楽しかった"),
                CreateInfo("susu", "おもしろかったぁ"),
                CreateInfo("次回", "楽しみ！"),
                CreateInfo("マサ", "一言ポナツエエエエエエエ"),
                CreateInfo("あかね", "次は勝つよ！！！"),
                CreateInfo("ゆう＠風鈴", "次はかつ"),
                CreateInfo("ぽろん", "負けた・・・"),
                CreateInfo("ehp", "この企画、シリーズ化してやりましょう"),
                CreateInfo("ぐっち", "会社辞めます"),
                CreateInfo("あくあん", "良かった"),
                CreateInfo("碧天", "ん？"),
                CreateInfo("大輔", "ＧＪ"),
                CreateInfo("名前", "面白かった"),
                CreateInfo("らりご", "楽しかったです！"),
                CreateInfo("かべひ", "今度は本気出す"),
                CreateInfo("ブルービー", "強かったね"),
                CreateInfo("むいむい", "おもしろかった"),
                CreateInfo("ｵｳﾃ", "ｱｰﾔｯﾁｬｯﾀﾖｰ"),
                CreateInfo("hamwo", "動中求静"),
                CreateInfo("Anon", "ガリレオ宜しく"),
                CreateInfo("くさ", "100万ほしい"),
                CreateInfo("名前", "またやって"),
                CreateInfo("屋敷", "うほ"),
                CreateInfo("黒子", "俺なら勝てた"),
                CreateInfo("ウティ", "あ、まけました"),
                CreateInfo("屋敷", "がんばれ"),
                CreateInfo("ゆう", "まけますた"),
                CreateInfo("酸化", "産科"),
                CreateInfo("りかと。", "西尾先生おつ！"),
                CreateInfo("me♪", "楽しかった"),
                CreateInfo("らったくん", "おつかれえええええええええええええええええええええええ"),
                CreateInfo("わたさん", "おつ～"),
                CreateInfo("西尾明", "ﾃｨﾛﾃｨﾛ"),
                CreateInfo("くるくるへあ", "チェス大好き"),
                CreateInfo("しるこ", "ポナンザ強かった悔しい"),
                CreateInfo("参加", "参加"),
                CreateInfo("山田", "楽しかったです"),
                CreateInfo("ジェシー", "羽生さんに勝てる者はいない"),
                CreateInfo("JSbahha", "西尾さんありがとう！"),
                CreateInfo("いの", "愛ちゃんかわいい！"),
                CreateInfo("章夫", "良かった"),
                CreateInfo("愛ちゃん", "愛してる"),
                CreateInfo("あるる", "解説の先生のお二人お疲れ様でした"),
                CreateInfo("有久", "おもろかったよ"),
                CreateInfo("ゲドーくん", "ギョギョギョ"),
                CreateInfo("ばふぁりん", "次回楽しみにしてるよー♪"),
                CreateInfo("いまむら", "お疲れ様でしたー"),
                CreateInfo("てるお", "お疲れ様でした"),
                CreateInfo("きりぷー", "愛ちゃんかわええ"),
                CreateInfo("西尾", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("kopin", "山本さん結婚おめ"),
                CreateInfo("西尾明", "ﾃｨﾛﾃｨﾛ"),
                CreateInfo("ヒュウ", "pona強すぎ"),
                CreateInfo("ゴキゲン", "たのしかったおおおおおおおおおおおおおおおおおおおおおおおおお"),
                CreateInfo("野生の突撃", "きもちよかった"),
                CreateInfo("おや？", "まだだったんだ"),
                CreateInfo("白峯", "いぇーい"),
                CreateInfo("かつ", "よかった！"),
                CreateInfo("ます", "みんなお疲れ様"),
                CreateInfo("けふと", "あああああああああああ"),
                CreateInfo("太郎", "ありがとうございました"),
                CreateInfo("畑", "楽しかったー"),
                CreateInfo("ジェシー", "勝てた試合だった"),
                CreateInfo("森内", "あ、負けました"),
                CreateInfo("スペース", "自分の名前 メッセージ 愛ちゃんかわいかったよ"),
                CreateInfo("りさる", "おつかれさんした"),
                CreateInfo("まくの", "ティロ"),
                CreateInfo("愛ちゃん", "愛してるお"),
                CreateInfo("森内俊之", "あ、勝ちました"),
                CreateInfo("take-y", "電王がんばれ！"),
                CreateInfo("いま", "お疲れ様でしたー"),
                CreateInfo("ふぁぶ", "へええええええええええええええええええ"),
                CreateInfo("くるくるへあ", "チェス大好きだ"),
                CreateInfo("いさ", "楽しかったね"),
                CreateInfo("ジェシー", "次は羽生さんを"),
                CreateInfo("神龍", "山本生きろ"),
                CreateInfo("ﾃｨﾛﾃｨﾛ", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("鳥さん", "みる"),
                CreateInfo("おい", "またね"),
                CreateInfo("らったくん", "西尾さんすきー"),
                CreateInfo("やす", "お疲れ"),
                CreateInfo("ネミ", "西尾先生第3回電王戦楽しみにしてます！"),
                CreateInfo("オロナンミンＣ", "Pona隙が無いよ（涙）"),
                CreateInfo("みっちょ", "お疲れ様?"),
                CreateInfo("りくや", "将棋がこんなにおもろいとは思いませんでした。わくわくしながら見ました。"),
                CreateInfo("ほげ", "てぃろてぃろてぃろ"),
                CreateInfo("カキフライ", "たのしかったぞえびふらいいいいいいい"),
                CreateInfo("さくら", "電王戦がんばるでーーー"),
                CreateInfo("きりんの翼", "愛ちゃんかわいい！！"),
                CreateInfo("てぃろてぃろ", "ﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛﾃｨﾛ"),
                CreateInfo("森内", "あ、次は勝ちます"),
                CreateInfo("T代まさし", "何の参加かわかりません"),
                CreateInfo("nekohachinyan", "ティロティロはないの？"),
                CreateInfo("ハスブレロ", "またやってほしい！"),
                CreateInfo("リッキー", "ポナ強い！！"),
                CreateInfo("katamari", "ティロティロティロティロ"),
                CreateInfo("たつろう", "頑張ろう"),
                CreateInfo("チェス", "白黒つけるぜ！"),
                CreateInfo("拓馬", "たのしかったよ～～～～～～"),
                CreateInfo("スラリン", "打倒ポナンザ"),
                CreateInfo("いれヴぁす", "西尾さんは天使"),
                CreateInfo("おっと", "勝つぞー"),
                CreateInfo("うっしー", "参加始めた時にはすでに大勢決してた・・。"),
                CreateInfo("あじフライ", "一成結婚おめでとおおおおおおおおおおお"),
                CreateInfo("kani", "矢内お疲れ"),
                CreateInfo("ken", "負けちゃったけど楽しかった"),
                CreateInfo("ほげ", "てぃろてぃろ"),
                CreateInfo("koenn", "ティロ"),
                CreateInfo("さくら", "電王"),
                CreateInfo("ば", "あざす"),
                CreateInfo("蘿蔔", "一成結婚おめ"),
                CreateInfo("まさにー", "何に使われるのかがわからない謎メッセージ"),
                CreateInfo("コンバット越前", "みんなお疲れ"),
                CreateInfo("飯野研二", "愛ちゃん最高"),
                CreateInfo("jujubey", "楽しかったああああ"),
                CreateInfo("かもめ", "乙"),
                CreateInfo("行方尚史", "二日酔いです"),
                CreateInfo("砂糖", "将棋ウォーズやらね"),
                CreateInfo("ぴんぽん", "みんなお疲れさま！楽しかった！"),
                CreateInfo("you", "楽しかった"),
                CreateInfo("がんも", "参りました"),
                CreateInfo("あい", "おつ"),
                CreateInfo("ｱｰﾔｯﾁｬｯﾀﾖｰ", "楽しかった"),
                CreateInfo("ぽる", "おもしろかった！！"),
                CreateInfo("やちま", "負けたけど楽しかったよ～"),
                CreateInfo("群青", "民主将棋たのしい"),
                CreateInfo("kei", "まぁまぁじゃ"),
                CreateInfo("あはは", "また宜しく"),
                CreateInfo("てっつん", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("羽生", "いい勝負だったよ"),
                CreateInfo("ステステ", "西尾総理"),
                CreateInfo("pon", "ぽにゃんぱすー"),
                CreateInfo("森内龍王名人", "あ名人です"),
                CreateInfo("参加", "参加したい"),
                CreateInfo("ﾃｨﾛ", "ﾀﾉｼｿｳﾀﾞﾈ"),
                CreateInfo("ココ", "コンピュータ強い"),
                CreateInfo("ティロティロ", "西尾先生だいすきだああああ"),
                CreateInfo("しょう", "負けて悔しいぜ"),
                CreateInfo("はま", "たのしかったです"),
                CreateInfo("ランバ", "勝ちたかった…"),
                CreateInfo("もふ", "はにゅううううううううううううううう"),
                CreateInfo("chappy", "ティロティロ"),
                CreateInfo("四間ビシャイニング", "参りました"),
                CreateInfo("ベーコン", "わーい"),
                CreateInfo("西尾", "ティロ"),
                CreateInfo("ai5", "面白かったよ"),
                CreateInfo("のに", "勝ちたかったー！"),
                CreateInfo("あり", "楽しかったこれでおｋ？"),
                CreateInfo("牧田新", "工藤ちゃん結婚してくれえええええええええええええええ"),
                CreateInfo("じろけん", "おもしろかったー"),
                CreateInfo("たろ", "面白かった"),
                CreateInfo("ヤンキー", "ティロティ路"),
                CreateInfo("アトリックス", "焼きそばおいしかった"),
                CreateInfo("ロキ", "ティロティロ"),
                CreateInfo("galvez", "ああああ"),
                CreateInfo("愁迷亭闇落", "この仇はプロが！！"),
                CreateInfo("ねこ", "悔しい"),
                CreateInfo("おれ", "いやだよ"),
                CreateInfo("じぶ", "おつー"),
                CreateInfo("燕ちゃん", "勝ちたかった(つд⊂)"),
                CreateInfo("ﾃｨﾛ", "？"),
                CreateInfo("ふわり", "かわいかった"),
                CreateInfo("したら", "ええやないか"),
                CreateInfo("ねこ", "ティロティロ"),
                CreateInfo("名称不明", "w"),
                CreateInfo("野々山峻", "これでいいですか？"),
                CreateInfo("かなぶん", "乙"),
                CreateInfo("風呂", "楽しかったー"),
                CreateInfo("ＮＡＲＵ", "おつぽよ"),
                CreateInfo("kac", "お疲れ様です"),
                CreateInfo("ほいやん", "ドラゴンタイガー"),
                CreateInfo("繁樹", "ポナンザ強い"),
                CreateInfo("ACU", "楽しかった"),
                CreateInfo("紳士", "楽しかったです"),
                CreateInfo("大平", "大平vs大平なら勝ってた"),
                CreateInfo("ロジウム", "まけたーー"),
                CreateInfo("名前", "メッセージ！！"),
                CreateInfo("あき", "ファイヤー！"),
                CreateInfo("ひょうすべ", "おもしろかった"),
                CreateInfo("春光", "おもろかった"),
                CreateInfo("天才", "たおす"),
                CreateInfo("しら＊たま", "楽しかった（小学生並みの感想）"),
                CreateInfo("繁樹", "面白かった"),
                CreateInfo("イーグルス", "0824 たのしい"),
                CreateInfo("吉野", "ティロフィナーレ"),
                CreateInfo("箱麟", "１１４５１４！"),
                CreateInfo("たれ蔵", "楽しかったおー"),
                CreateInfo("横山緑", "やい！"),
                CreateInfo("森内", "あ、参加しました"),
                CreateInfo("doyanza", "( ･´ｰ･｀)"),
                CreateInfo("森内", "あ、勝ちました"),
                CreateInfo("森内俊之", "あ、負けました"),
                CreateInfo("うめ", "ティロ"),
                CreateInfo("王将", "餃子たべたくなった"),
                CreateInfo("ルカ", "悔しいぃ～"),
                CreateInfo("すぎもつ", "将棋だいすきです"),
                CreateInfo("baysian", "楽しかったです"),
                CreateInfo("ジュンタ", "またやろう"),
                CreateInfo("iness", "ジョイナス"),
                CreateInfo("アンフィ", "がんばって～～"),
                CreateInfo("じゃね", "皆さんお疲れ様でした"),
                CreateInfo("ジュンペー", "初段です"),
                CreateInfo("シン", "次だ！"),
                CreateInfo("吉野", "ティロフィナーレ！"),
                CreateInfo("ポテト", "強い（確信）"),
                CreateInfo("愛ちゃん、俺だ", "結婚してくれ"),
                CreateInfo("Q", "！"),
                CreateInfo("あさやん", "いいね！"),
                CreateInfo("凹○", "電王戦に期待！"),
                CreateInfo("俺様", "愛ちゃんかわいい"),
                CreateInfo("たっつー", "よかった"),
                CreateInfo("さと", "お疲れさまでした"),
                CreateInfo("かに", "お疲れ様でした"),
                CreateInfo("とも", "片思いしています。実るといいな"),
                CreateInfo("焼き芋", "もう１戦やろう"),
                CreateInfo("まひろ", "成し遂げたぜ。"),
                CreateInfo("将棋仮面", "えびガチガチすぎｗｗｗ"),
                CreateInfo("ぽぽ", "お疲れ様でした"),
                CreateInfo("ﾎﾟﾝ太", "電王戦楽しみ"),
                CreateInfo("falette", "たのしかったぜー"),
                CreateInfo("？？？", "わかんない"),
                CreateInfo("あんきも", "楽しかった"),
                CreateInfo("みすたぁ", "わこつ"),
                CreateInfo("秋", "リベンジ！"),
                CreateInfo("MISO", "面白かったよ～"),
                CreateInfo("さばふぐ", "おもろかった"),
                CreateInfo("箱麟", "楽しかった"),
                CreateInfo("ティロ", "チキン"),
                CreateInfo("たれ蔵", "楽しかった"),
                CreateInfo("栗", "ｂ"),
                CreateInfo("mm", "ティロ"),
                CreateInfo("デーヒー", "おつ"),
                CreateInfo("森内　あ", "負けました"),
                CreateInfo("Thunders", "めっさおもしろかったです。"),
                CreateInfo("やなぎは", "面白かった"),
                CreateInfo("森内", "あ、負けました"),
            };

            var liveOwnerList = new List<string>
            {
                "のぼる",
	            "二次元人",
	            "にくくい",
	            "かど",	
	            "メイビス",
	            "森太",
	            "たかし",
	            "にしにっぽん",
	            "オグリ",
	            "ねんのために",
	            "うぬこうじ",
	            "不☆通",
	            "人参",
	            "ベルシタス",
	            "できすぎ",
	            "サスケ",
	            "龍氣槍",
	            "みーご",
	            "ルカワ",
	            "616",
	            "らふぃ",	
	            "かるあ",
	            "るーせる",
	            "ねぎま",
	            "じゃんぼ",
	            "生ちゃん",
	            "うにうに",
	            "kendo-arashi",
	            "さまんさneo",
	            "みどりの"
            };

            var voterList = new VoterList
            {
                UnjoinedVoterCount = 236,
                DonorAmount = 160000,
                TotalLiveCount = 100,
                TotalLiveVisitorCount = 1000,
                TotalLiveCommentCount = 120000,
            };
            var x = new List<VoterInfo>(list);
            Enumerable.Range(0, 50)
                .ForEach(_ => x.AddRange(list));
            voterList.JoinedVoterList.AddRange(x);

            voterList.DonorViewList.AddRange(
                list.OrderBy(_ => Guid.NewGuid())
                    .Select(_ => _.Name));

            voterList.LiveOwnerList.AddRange(
                from name in liveOwnerList
                select new VoterInfo
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = name,
                });

            return voterList;
        }
    }
}
