#pragma warning disable 1591 
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CommenterProtocol.proto
// Note: requires additional types generated from: Protocol.inc.proto
namespace VoteSystem.Protocol.Commenter
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyNewLiveCommand")]
  public partial class NotifyNewLiveCommand : global::ProtoBuf.IExtensible
  {
    public NotifyNewLiveCommand() {}
    
    private VoteSystem.Protocol.LiveData _Live;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Live", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData Live
    {
      get { return _Live; }
      set { _Live = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyClosedLiveCommand")]
  public partial class NotifyClosedLiveCommand : global::ProtoBuf.IExtensible
  {
    public NotifyClosedLiveCommand() {}
    
    private VoteSystem.Protocol.LiveData _Live;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Live", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData Live
    {
      get { return _Live; }
      set { _Live = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LiveConnectedCommand")]
  public partial class LiveConnectedCommand : global::ProtoBuf.IExtensible
  {
    public LiveConnectedCommand() {}
    
    private VoteSystem.Protocol.LiveData _Live;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Live", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData Live
    {
      get { return _Live; }
      set { _Live = value; }
    }
    private int _LiveRoom;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"LiveRoom", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LiveRoom
    {
      get { return _LiveRoom; }
      set { _LiveRoom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LiveDisconnectedCommand")]
  public partial class LiveDisconnectedCommand : global::ProtoBuf.IExtensible
  {
    public LiveDisconnectedCommand() {}
    
    private VoteSystem.Protocol.LiveData _Live;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Live", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData Live
    {
      get { return _Live; }
      set { _Live = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommenterStateChangedCommand")]
  public partial class CommenterStateChangedCommand : global::ProtoBuf.IExtensible
  {
    public CommenterStateChangedCommand() {}
    
    private VoteSystem.Protocol.LiveData _Live;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Live", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData Live
    {
      get { return _Live; }
      set { _Live = value; }
    }
    private bool _CanPostComment;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"CanPostComment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool CanPostComment
    {
      get { return _CanPostComment; }
      set { _CanPostComment = value; }
    }
    private bool _IsWatching;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"IsWatching", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool IsWatching
    {
      get { return _IsWatching; }
      set { _IsWatching = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotificationForPostCommand")]
  public partial class NotificationForPostCommand : global::ProtoBuf.IExtensible
  {
    public NotificationForPostCommand() {}
    
    private VoteSystem.Protocol.Notification _Notification;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Notification", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.Notification Notification
    {
      get { return _Notification; }
      set { _Notification = value; }
    }
    private VoteSystem.Protocol.LiveData _ToLive;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ToLive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public VoteSystem.Protocol.LiveData ToLive
    {
      get { return _ToLive; }
      set { _ToLive = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}