#!/bin/sh

### BEGIN INIT INFO
# Provides:		VoteServer
# Required-Start:	
# Required-Stop:	
# Default-Start:	3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Server for the VoteSystem
### END INIT INFO

test -f /usr/sbin/cron || exit 0

#PIDFILE=/var/run/vote-server.pid
PIDFILE=/tmp/vote-server.pid
SERVER_DIR=/home/ebifrier/programs/VoteSystem/VoteServer
SERVER=${SERVER_DIR}/../bin/VoteServer.exe
DAEMON=/usr/bin/mono-service2
USER=ebifrier

. /lib/lsb/init-functions

start() {
    log_daemon_msg "Starting vote-system server" "Server"

    cd $SERVER_DIR
    $DAEMON -l:$PIDFILE $SERVER
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping vote-system server" "Server"

    if [ -f "$PIDFILE" ]; then
	kill `cat $PIDFILE`
	RETVAL="$?"

	[ $RETVAL -eq 0 ] && rm -f $PIDFILE
    else
	RETVAL=1
    fi

    log_end_msg $RETVAL
}

status() {
    log_action_begin_msg "Checking vote-system server"
    if pidofproc -p "$PIDFILE" >/dev/null; then
        log_action_end_msg 0 "running"
        exit 0
    else
        if [ -e "$PIDFILE" ]; then
            log_action_end_msg 1 "failed to start"
            exit 1
        else
            log_action_end_msg 0 "not running"
            exit 3
        fi
    fi
}

case "$1" in
start)
	start
	;;
stop)
	stop
        ;;
restart)
	stop
	start
	;;
status)
	status
	;;
*)	log_action_msg "Usage: /etc/init.d/vote-server {start|stop|status|restart}"
        exit 2
        ;;
esac
exit 0
